-- CREATE TABLE "publisher"
-- (
-- 	publisher_id integer PRIMARY KEY,
-- 	name varchar(32),
-- 	city varchar(32)
-- );
-- CREATE TABLE "book"
-- (
-- 	book_id integer PRIMARY KEY,
-- 	author varchar(32),
-- 	title varchar(32)
-- );
